<error>
  <time>02:43:43</time>
  <job>FLOW</job>
  <reason>Process exited with status code 1</reason>
  <stderr>
Traceback (most recent call last):
  File &quot;/usr/local/lib/python3.8/dist-packages/ert/shared/share/ert/forward-models/res/script/flow.py&quot;, line 9, in &lt;module&gt;
    run(config, [arg for arg in sys.argv[1:] if len(arg) &gt; 0])
  File &quot;/usr/local/lib/python3.8/dist-packages/ert/shared/share/ert/forward-models/res/script/ecl_run.py&quot;, line 552, in run
    run.runEclipse()
  File &quot;/usr/local/lib/python3.8/dist-packages/ert/shared/share/ert/forward-models/res/script/ecl_run.py&quot;, line 388, in runEclipse
    raise subprocess.CalledProcessError(return_code, command)
subprocess.CalledProcessError: Command &apos;[&apos;/usr/bin/flow&apos;, &apos;SPE3&apos;]&apos; returned non-zero exit status 1.
</stderr>
  <stderr_file>/home/aaronyf/download/ert/ert-spe3flow/spe3_out/realization-0/iter-0/FLOW.stderr.1</stderr_file>
</error>
