2024-10-09 01:48:30,508 - root - MainThread - DEBUG - ERT Plugin manager:
	ert.shared.hook_implementations
		<HookCaller 'help_links'>
		<HookCaller 'installable_jobs'>
		<HookCaller 'installable_workflow_jobs'>
		<HookCaller 'job_documentation'>
		<HookCaller 'legacy_ertscript_workflow'>
		<HookCaller 'site_config_lines'>

2024-10-09 01:48:30,508 - root - MainThread - DEBUG - Creating temporary directory for site-config
2024-10-09 01:48:30,508 - root - MainThread - DEBUG - Temporary directory created: /tmp/tmp5r1b3ego
2024-10-09 01:48:30,509 - root - MainThread - DEBUG - Got no ecl100 config path from any plugins
2024-10-09 01:48:30,509 - root - MainThread - DEBUG - Got no ecl300 config path from any plugins
2024-10-09 01:48:30,509 - root - MainThread - DEBUG - Got no flow config path from any plugins
2024-10-09 01:48:30,509 - root - MainThread - DEBUG - Got no rms config path from any plugins
2024-10-09 01:48:30,514 - root - MainThread - DEBUG - Creating temporary site-config
2024-10-09 01:48:30,514 - root - MainThread - DEBUG - Temporary site-config created: /tmp/tmp5r1b3ego/site-config
2024-10-09 01:48:30,514 - root - MainThread - DEBUG - Setting environment variable ERT_SITE_CONFIG=/tmp/tmp5r1b3ego/site-config
2024-10-09 01:48:30,514 - ert.__main__ - MainThread - INFO - Running ert with Namespace(color_always=False, config='spe3.ert', current_ensemble='default', disable_monitoring=False, feature_scheduler=None, func=<function run_cli at 0x7ff1ea034430>, logdir='./logs', mode='test_run', port_range=None, read_only=False, verbose=False)
2024-10-09 01:48:30,638 - ert.config.ert_config - MainThread - INFO - Content of the configuration file (spe3.ert):
QUEUE_SYSTEM LOCAL
QUEUE_OPTION LOCAL MAX_RUNNING 4
RUNPATH spe3_out/realization-<IENS>/iter-<ITER>
NUM_REALIZATIONS 12
ECLBASE SPE3
REFCASE <CONFIG_PATH>/resources/refcase/SPE3
SUMMARY WOPR:PROD FOPR WOPT:PROD FOPT BOSAT BRS WBHP:INJ WBHP:INJ WGIR:PROD WGIR:INJ WGPR:INJ WGPR:PROD WOIR:PROD WOIR:INJ WWIR:PROD WWIR:INJ WWPR:PROD WWPR:INJ
OBS_CONFIG obs.txt
GEN_KW FIELD_PROPERTIES field_properties_priors

2024-10-09 01:48:30,638 - ert.config.ert_config - MainThread - INFO - Content of the config_dict: {'DEFINE': [['<CONFIG_PATH>', '/home/aaronyf/download/ert/ert-spe3flow'], ['<CONFIG_FILE_BASE>', 'spe3'], ['<DATE>', '2024-10-09'], ['<CWD>', '/home/aaronyf/download/ert/ert-spe3flow'], ['<CONFIG_FILE>', 'spe3.ert']], 'JOB_SCRIPT': 'job_dispatch.py', 'QUEUE_SYSTEM': <QueueSystem.LOCAL: 'LOCAL'>, 'QUEUE_OPTION': [[<QueueSystem.LOCAL: 'LOCAL'>, 'MAX_RUNNING', '1'], [<QueueSystem.LOCAL: 'LOCAL'>, 'MAX_RUNNING', '4']], 'INSTALL_JOB': [['delete_file', '/usr/local/lib/python3.8/dist-packages/ert/shared/share/ert/forward-models/shell/delete_file'], ['careful_copy_file', '/usr/local/lib/python3.8/dist-packages/ert/shared/share/ert/forward-models/shell/careful_copy_file'], ['delete_directory', '/usr/local/lib/python3.8/dist-packages/ert/shared/share/ert/forward-models/shell/delete_directory'], ['copy_file', '/usr/local/lib/python3.8/dist-packages/ert/shared/share/ert/forward-models/shell/copy_file'], ['copy_directory', '/usr/local/lib/python3.8/dist-packages/ert/shared/share/ert/forward-models/shell/copy_directory'], ['make_symlink', '/usr/local/lib/python3.8/dist-packages/ert/shared/share/ert/forward-models/shell/make_symlink'], ['symlink', '/usr/local/lib/python3.8/dist-packages/ert/shared/share/ert/forward-models/shell/symlink'], ['move_file', '/usr/local/lib/python3.8/dist-packages/ert/shared/share/ert/forward-models/shell/move_file'], ['make_directory', '/usr/local/lib/python3.8/dist-packages/ert/shared/share/ert/forward-models/shell/make_directory'], ['eclipse300', '/usr/local/lib/python3.8/dist-packages/ert/shared/share/ert/forward-models/res/eclipse300'], ['flow', '/usr/local/lib/python3.8/dist-packages/ert/shared/share/ert/forward-models/res/flow'], ['eclipse100', '/usr/local/lib/python3.8/dist-packages/ert/shared/share/ert/forward-models/res/eclipse100'], ['rms', '/usr/local/lib/python3.8/dist-packages/ert/shared/share/ert/forward-models/res/rms'], ['template_render', '/usr/local/lib/python3.8/dist-packages/ert/shared/share/ert/forward-models/templating/template_render'], ['MAKE_DIRECTORY', '/usr/local/lib/python3.8/dist-packages/ert/shared/share/ert/forward-models/old_style/MAKE_DIRECTORY'], ['MAKE_SYMLINK', '/usr/local/lib/python3.8/dist-packages/ert/shared/share/ert/forward-models/old_style/MAKE_SYMLINK'], ['MOVE_FILE', '/usr/local/lib/python3.8/dist-packages/ert/shared/share/ert/forward-models/old_style/MOVE_FILE'], ['ECLIPSE300', '/usr/local/lib/python3.8/dist-packages/ert/shared/share/ert/forward-models/old_style/ECLIPSE300'], ['DELETE_FILE', '/usr/local/lib/python3.8/dist-packages/ert/shared/share/ert/forward-models/old_style/DELETE_FILE'], ['SYMLINK', '/usr/local/lib/python3.8/dist-packages/ert/shared/share/ert/forward-models/old_style/SYMLINK'], ['ECLIPSE100', '/usr/local/lib/python3.8/dist-packages/ert/shared/share/ert/forward-models/old_style/ECLIPSE100'], ['COPY_FILE', '/usr/local/lib/python3.8/dist-packages/ert/shared/share/ert/forward-models/old_style/COPY_FILE'], ['FLOW', '/usr/local/lib/python3.8/dist-packages/ert/shared/share/ert/forward-models/old_style/FLOW'], ['TEMPLATE_RENDER', '/usr/local/lib/python3.8/dist-packages/ert/shared/share/ert/forward-models/old_style/TEMPLATE_RENDER'], ['DELETE_DIRECTORY', '/usr/local/lib/python3.8/dist-packages/ert/shared/share/ert/forward-models/old_style/DELETE_DIRECTORY'], ['COPY_DIRECTORY', '/usr/local/lib/python3.8/dist-packages/ert/shared/share/ert/forward-models/old_style/COPY_DIRECTORY'], ['RMS', '/usr/local/lib/python3.8/dist-packages/ert/shared/share/ert/forward-models/old_style/RMS'], ['CAREFUL_COPY_FILE', '/usr/local/lib/python3.8/dist-packages/ert/shared/share/ert/forward-models/old_style/CAREFUL_COPY_FILE']], 'RUNPATH': '/home/aaronyf/download/ert/ert-spe3flow/spe3_out/realization-<IENS>/iter-<ITER>', 'NUM_REALIZATIONS': 12, 'ECLBASE': 'SPE3', 'REFCASE': '/home/aaronyf/download/ert/ert-spe3flow/resources/refcase/SPE3', 'SUMMARY': [['WOPR:PROD', 'FOPR', 'WOPT:PROD', 'FOPT', 'BOSAT', 'BRS', 'WBHP:INJ', 'WBHP:INJ', 'WGIR:PROD', 'WGIR:INJ', 'WGPR:INJ', 'WGPR:PROD', 'WOIR:PROD', 'WOIR:INJ', 'WWIR:PROD', 'WWIR:INJ', 'WWPR:PROD', 'WWPR:INJ']], 'OBS_CONFIG': '/home/aaronyf/download/ert/ert-spe3flow/obs.txt', 'GEN_KW': [['FIELD_PROPERTIES', '/home/aaronyf/download/ert/ert-spe3flow/field_properties_priors']]}
2024-10-09 01:48:30,645 - ert.config.ensemble_config - MainThread - INFO - Adding GenKwConfig config (of size 3) to parameter_configs
2024-10-09 01:48:30,926 - ert.cli.main - MainThread - INFO - Config contains forward model step TEMPLATE_RENDER
2024-10-09 01:48:30,926 - ert.cli.main - MainThread - INFO - Config contains forward model step FLOW
2024-10-09 01:48:30,932 - ert.cli.model_factory - MainThread - INFO - Initiating experiment
2024-10-09 01:48:30,932 - ert.enkf_main - MainThread - INFO - To repeat this experiment, add the following random seed to your config file:
2024-10-09 01:48:30,932 - ert.enkf_main - MainThread - INFO - RANDOM_SEED 153109182695904743681444289941544070615
2024-10-09 01:48:31,122 - ert.cli.main - MainThread - WARNING - ERT is running in an existing runpath
2024-10-09 01:48:31,149 - ert.enkf_main - ert_cli_simulation_thread - INFO - To repeat this experiment, add the following random seed to your config file:
2024-10-09 01:48:31,149 - ert.enkf_main - ert_cli_simulation_thread - INFO - RANDOM_SEED 111910972612799938258330194810643893863
2024-10-09 01:48:31,149 - ert.config.gen_kw_config - ert_cli_simulation_thread - INFO - Sampling parameter FIELD_PROPERTIES for realization 0
2024-10-09 01:48:31,155 - ert.enkf_main - ert_cli_simulation_thread - DEBUG - sample_prior() time_used 0.0056s
2024-10-09 01:48:31,167 - ert.enkf_main - ert_cli_simulation_thread - DEBUG - create_run_path() time_used 0.0123s
2024-10-09 01:48:31,628 - ert.scheduler - LegacyEnsemble - INFO - Experiment ran on ORCHESTRATOR: scheduler on LOCAL queue
2024-10-09 01:48:31,736 - ert.scheduler.local_driver - LegacyEnsemble - DEBUG - Submitting realization 0 as command 'job_dispatch.py /home/aaronyf/download/ert/ert-spe3flow/spe3_out/realization-0/iter-0'
2024-10-09 01:48:32,717 - ert.scheduler.local_driver - LegacyEnsemble - INFO - Realization 0 finished with returncode=-9
2024-10-09 01:48:32,717 - ert.scheduler.job - LegacyEnsemble - WARNING - Realization 0 failed, resubmitting for attempt 2 of 2
2024-10-09 01:48:32,718 - ert.scheduler.local_driver - LegacyEnsemble - DEBUG - Submitting realization 0 as command 'job_dispatch.py /home/aaronyf/download/ert/ert-spe3flow/spe3_out/realization-0/iter-0'
2024-10-09 01:48:33,736 - ert.scheduler.local_driver - LegacyEnsemble - INFO - Realization 0 finished with returncode=-9
2024-10-09 01:48:33,737 - ert.scheduler.job - LegacyEnsemble - ERROR - Realization: 0 failed after reaching max submit (2):
	
2024-10-09 01:48:33,737 - ert.scheduler.job - LegacyEnsemble - ERROR - job FLOW failed with: 'Process exited with status code 1'
	stderr file: '/home/aaronyf/download/ert/ert-spe3flow/spe3_out/realization-0/iter-0/FLOW.stderr.1',
	its contents:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ert/shared/share/ert/forward-models/res/script/flow.py", line 9, in <module>
    run(config, [arg for arg in sys.argv[1:] if len(arg) > 0])
  File "/usr/local/lib/python3.8/dist-packages/ert/shared/share/ert/forward-models/res/script/ecl_run.py", line 552, in run
    run.runEclipse()
  File "/usr/local/lib/python3.8/dist-packages/ert/shared/share/ert/forward-models/res/script/ecl_run.py", line 388, in runEclipse
    raise subprocess.CalledProcessError(return_code, command)
subprocess.CalledProcessError: Command '['/usr/bin/flow', 'SPE3']' returned non-zero exit status 1.

2024-10-09 01:48:33,739 - ert.scheduler.local_driver - LegacyEnsemble - INFO - All realization tasks finished
2024-10-09 01:48:33,740 - ert.scheduler - LegacyEnsemble - INFO - Experiment ran on QUEUESYSTEM: LOCAL
2024-10-09 01:48:37,239 - root - MainThread - DEBUG - Resetting environment variable ERT_SITE_CONFIG
2024-10-09 01:48:37,239 - root - MainThread - DEBUG - Deleting temporary directory for site-config
2024-10-09 01:48:37,239 - ert.__main__ - MainThread - ERROR - Experiment failed!
Realization: 0 failed after reaching max submit (2):
	
job FLOW failed with: 'Process exited with status code 1'
	stderr file: '/home/aaronyf/download/ert/ert-spe3flow/spe3_out/realization-0/iter-0/FLOW.stderr.1',
	its contents:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ert/shared/share/ert/forward-models/res/script/flow.py", line 9, in <module>
    run(config, [arg for arg in sys.argv[1:] if len(arg) > 0])
  File "/usr/local/lib/python3.8/dist-packages/ert/shared/share/ert/forward-models/res/script/ecl_run.py", line 552, in run
    run.runEclipse()
  File "/usr/local/lib/python3.8/dist-packages/ert/shared/share/ert/forward-models/res/script/ecl_run.py", line 388, in runEclipse
    raise subprocess.CalledProcessError(return_code, command)
subprocess.CalledProcessError: Command '['/usr/bin/flow', 'SPE3']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ert/__main__.py", line 670, in main
    args.func(args, context.plugin_manager)
  File "/usr/local/lib/python3.8/dist-packages/ert/cli/main.py", line 135, in run_cli
    model.reraise_exception(ErtCliError)
  File "/usr/local/lib/python3.8/dist-packages/ert/run_models/base_run_model.py", line 366, in reraise_exception
    raise exctype(self.getFailMessage()).with_traceback(
  File "/usr/local/lib/python3.8/dist-packages/ert/run_models/base_run_model.py", line 304, in start_simulations_thread
    run_context = self.run_experiment(
  File "/usr/local/lib/python3.8/dist-packages/ert/run_models/ensemble_experiment.py", line 88, in run_experiment
    self._evaluate_and_postprocess(prior_context, evaluator_server_config)
  File "/usr/local/lib/python3.8/dist-packages/ert/run_models/base_run_model.py", line 707, in _evaluate_and_postprocess
    self.checkHaveSufficientRealizations(
  File "/usr/local/lib/python3.8/dist-packages/ert/run_models/single_test_run.py", line 38, in checkHaveSufficientRealizations
    raise ErtRunError("Experiment failed!")
ert.cli.main.ErtCliError: Experiment failed!
Realization: 0 failed after reaching max submit (2):
	
job FLOW failed with: 'Process exited with status code 1'
	stderr file: '/home/aaronyf/download/ert/ert-spe3flow/spe3_out/realization-0/iter-0/FLOW.stderr.1',
	its contents:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/ert/shared/share/ert/forward-models/res/script/flow.py", line 9, in <module>
    run(config, [arg for arg in sys.argv[1:] if len(arg) > 0])
  File "/usr/local/lib/python3.8/dist-packages/ert/shared/share/ert/forward-models/res/script/ecl_run.py", line 552, in run
    run.runEclipse()
  File "/usr/local/lib/python3.8/dist-packages/ert/shared/share/ert/forward-models/res/script/ecl_run.py", line 388, in runEclipse
    raise subprocess.CalledProcessError(return_code, command)
subprocess.CalledProcessError: Command '['/usr/bin/flow', 'SPE3']' returned non-zero exit status 1.

2024-10-09 01:48:37,240 - root - MainThread - INFO - Peak memory use: 261868 kB
